"This test shows that classes are instances of their metaclasses which are instances of Metaclass. Since Metaclass is also a class, it is an instance of its metaclass as well."

Transcript show: 'test' class; cr.
Transcript show: 'test' class class; cr.
Transcript show: 'test' class class class; cr.
Transcript show: 'test' class class class class; cr.
Transcript show: 'test' class class class class class; cr.
Transcript show: 'test' class class class class class class; cr.
